Imports System.Data.OleDb

Public Class frmAddUser
    Private Sub btnSave_Click(sender As Object, e As EventArgs) Handles btnSave.Click

        If txtUsername.Text = "" Or txtPassword.Text = "" Or txtFirstName.Text = "" Or txtLastName.Text = "" Or txtEmail.Text = "" Then
            MessageBox.Show("Please fill out all required fields.", "Missing Data", MessageBoxButtons.OK, MessageBoxIcon.Warning)
            Return
        End If

        Dim transaction As OleDbTransaction = Nothing

        Try
            OpenConnection()
            transaction = conn.BeginTransaction()

            Dim query1 As String = "INSERT INTO tblUsers (Username, [Password], Role, Email) VALUES (@user, @pass, @role, @email)"
            Dim cmd As New OleDbCommand(query1, conn, transaction)

            cmd.Parameters.AddWithValue("@user", txtUsername.Text)
            cmd.Parameters.AddWithValue("@pass", txtPassword.Text)
            cmd.Parameters.AddWithValue("@role", cmbRole.SelectedItem.ToString())
            cmd.Parameters.AddWithValue("@email", txtEmail.Text)

            cmd.ExecuteNonQuery()
            cmd.CommandText = "SELECT @@IDENTITY"
            cmd.Parameters.Clear()

            Dim newUserID As Integer = Convert.ToInt32(cmd.ExecuteScalar())

            MessageBox.Show("Debug: The new UserID generated by Access is " & newUserID)

            Dim query2 As String = "INSERT INTO tblEmployees (UserID, FirstName, LastName, ContactNumber, BaseSalary, CommissionRate) VALUES (@uid, @fname, @lname, @contact, @salary, @comm)"
            Dim cmd2 As New OleDbCommand(query2, conn, transaction)

            cmd2.Parameters.AddWithValue("@uid", newUserID)
            cmd2.Parameters.AddWithValue("@fname", txtFirstName.Text)
            cmd2.Parameters.AddWithValue("@lname", txtLastName.Text)
            cmd2.Parameters.AddWithValue("@contact", txtContact.Text)
            cmd2.Parameters.AddWithValue("@salary", Convert.ToDecimal(txtSalary.Text))

            Dim commDecimal As Decimal = Convert.ToDecimal(txtCommission.Text) / 100
            cmd2.Parameters.AddWithValue("@comm", commDecimal)

            cmd2.ExecuteNonQuery()

            transaction.Commit()

            MessageBox.Show("New user created successfully!", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information)
            Me.Close()

        Catch ex As Exception
            If transaction IsNot Nothing Then
                transaction.Rollback()
            End If
            MessageBox.Show("Database Error: " & ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error)
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub btnCancel_Click(sender As Object, e As EventArgs) Handles btnCancel.Click
        Me.Close()
    End Sub

    Private Sub lblExit_Click(sender As Object, e As EventArgs) Handles lblExit.Click
        Me.Close()
    End Sub

End Class